version: '3'
services: 
  web-1:
    build: . 
    ports:
    - 3000
  web-2:
    build: . 
    ports:
    - 3001
  web-3:
    build: . 
    ports:
    - 3002
  load-balancer:
    build: nginx/
    ports:
      - 80:80
    links:
      - web-1
      - web-2
      - web-3